Fix REPOSITORY_URL check and add debug info

diff --git a/.github/workflows/event-logger.yml b/.github/workflows/event-logger.yml
--- a/.github/workflows/event-logger.yml
+++ b/.github/workflows/event-logger.yml
@@ -54,3 +54,12 @@ jobs:
           echo $COMMITS > commits.json
           cat commits.json # debugging
           pipenv run gitcommitlogger -r $(echo $REPOSITORY_URL) -t $(echo $EVENT_TYPE) -i commits.json -o commit_stats.csv -u $(echo $COMMIT_LOG_API) -v
+      - name: Log pull request closed and merged
+        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
+        run: |
+          echo "Repository URL: ${REPOSITORY_URL}"  # Print the Repository URL for debugging
+          f [ -z "${REPOSITORY_URL}" ]; then
+          echo "Error: REPOSITORY_URL is empty."
+          exit 1  # Exit the workflow with an error if REPOSITORY_URL is empty
+          fi
+          pipenv run gitcommitlogger -r ${REPOSITORY_URL} -u ${GITHUB_LOGIN} --t ${PR_CLOSED_AT} --merged -o commit_stats.csv -v ${COMMIT_LOG_API}
